# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-05 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverifyrecord_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='license_image',
            field=models.ImageField(default='license_image/default.png', upload_to='License_image/%Y/%m'),
        ),
    ]
